FROM node:17.3-alpine as builder
WORKDIR /app
RUN apk update && apk add mysql-client
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install
RUN npx prisma generate
EXPOSE 3000
