version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
