version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app:cached
      - /app/node_modules
    ports:
      - "3000:3000"
    command: "npm run dev"
  db:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: express_demo_development
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
    - 3306:3306
